#!/usr/bin/env python3
"""Normalize gaps[] entries AND dedupe against models[].updates.bench fills.

Two phases:
1. Reshape {modelId, benchKey} -> {modelId, field, triedFormats[]} schema.
2. Drop gaps whose (modelId, field) is already filled in models[].updates.bench.

MX1 invariant: every (active_model, core_bench) cell lands in EXACTLY ONE of
filled | gaps | notApplicable.
"""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent


def main() -> int:
    p = ROOT / ".aicodermap-agent-out.json"
    with open(p, encoding="utf-8") as _f:
        art = json.load(_f)

    # Build the set of filled (modelId, field) pairs:
    # 1. Existing data/models.json bench values (will persist post-merge)
    # 2. New artifact models[].updates.bench (synth claims)
    filled: set[tuple[str, str]] = set()
    data_path = ROOT / "data" / "models.json"
    if data_path.exists():
        with open(data_path, encoding="utf-8") as _f:
            existing = json.load(_f)
        existing_list = (
            existing if isinstance(existing, list) else existing.get("models", [])
        )
        for m in existing_list:
            mid = m.get("id")
            if not mid:
                continue
            bench = m.get("bench") or {}
            for k, v in bench.items():
                if v is not None and v != "" and v != "?" and v != "Unknown":
                    filled.add((mid, k))
    for m in art.get("models") or []:
        mid = m.get("id") or m.get("modelId")
        if not mid:
            continue
        bench = (m.get("updates") or {}).get("bench") or {}
        for k, v in bench.items():
            if v is not None:
                filled.add((mid, k))

    # Normalize each gap entry; drop those whose (mid, field) is filled.
    out: list = []
    reshape_count = 0
    dropped_overlap = 0
    pass_count = 0
    for g in art.get("gaps") or []:
        if not isinstance(g, dict):
            continue
        # Handle {key: "modelId.field"} form
        if "key" in g and isinstance(g["key"], str) and "." in g["key"]:
            mid, field = g["key"].split(".", 1)
            if (mid, field) in filled:
                dropped_overlap += 1
                continue
            if "triedFormats" not in g:
                g["triedFormats"] = ["unknown"]
            if "triedSources" not in g:
                g["triedSources"] = []
            if "triedQueries" not in g:
                g["triedQueries"] = []
            out.append(g)
            pass_count += 1
            continue
        # Already {modelId, field} form
        if "modelId" in g and "field" in g:
            mid, field = g["modelId"], g["field"]
            if (mid, field) in filled:
                dropped_overlap += 1
                continue
            if "triedFormats" not in g:
                g["triedFormats"] = ["unknown"]
            if "triedSources" not in g:
                g["triedSources"] = []
            if "triedQueries" not in g:
                g["triedQueries"] = []
            out.append(g)
            pass_count += 1
            continue
        # {modelId, benchKey} form — needs reshape
        if "modelId" in g and "benchKey" in g:
            mid, field = g["modelId"], g["benchKey"]
            if (mid, field) in filled:
                dropped_overlap += 1
                continue
            new_g = {
                "modelId": mid,
                "field": field,
                "triedSources": list(g.get("triedSources") or []),
                "triedQueries": list(g.get("triedQueries") or []),
                "triedFormats": list(g.get("triedFormats") or ["unknown"]),
            }
            src = g.get("source")
            if src and src not in new_g["triedSources"]:
                new_g["triedSources"].append(src)
            reason = g.get("reason") or g.get("note")
            if reason:
                new_g["reason"] = reason
            if g.get("autoGenerated"):
                new_g["autoGenerated"] = True
            out.append(new_g)
            reshape_count += 1
            continue
        # Unrecognized shape — drop
    art["gaps"] = out
    with open(p, "w", encoding="utf-8") as f:
        json.dump(art, f, ensure_ascii=False, indent=2)
    print(f"filled-cells: {len(filled)}")
    print(
        f"gaps: reshape={reshape_count} pass-through={pass_count} dropped-overlap={dropped_overlap} total={len(out)}"
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
